# Generated by Django 3.2.9 on 2021-11-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeature', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
