# Generated by Django 3.2.9 on 2021-11-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeature', '0002_auto_20211121_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.CharField(max_length=10),
        ),
    ]
