# Generated by Django 3.2.9 on 2021-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeature', '0003_auto_20211121_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
